apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: lamp-wp-aresucarini


  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: lamp-service
spec:
  type: LoadBalancer
  selector:
    app: lamp-wp-aresucarini
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008